import Head from 'next/head'
import { useRouter } from 'next/router'
import { FormEvent, useState } from 'react'
import styles from '../styles/Home.module.css'

export default function Home() {
  const [name, setName] = useState("")
  const [cnpj, setCnpj] = useState("")
  const [cidade, setCidade] = useState("")
  const router = useRouter()

  const fornecedorRegister = (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault()
    router.push(`/ver-fornecedor?name=${name}&cnpj=${cnpj}&cidade=${cidade}`)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Cadastrar Fornecedor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <form onSubmit={fornecedorRegister} className={styles.main}>
        <input placeholder="Nome" onChange={(e) => setName(e.target.value)} />
        <input placeholder="CNPJ" onChange={(e) => setCnpj(e.target.value)} />
        <input placeholder="Cidade" onChange={(e) => setCidade(e.target.value)} />
        <button type="submit">Enviar</button>
        <a onClick={() => router.push('/')}>Cadastrar Usuário</a>
      </form>
    </div>
  )
}
