import { GetServerSideProps } from 'next'
import Head from 'next/head'
import { useRouter } from 'next/router'
import styles from '../styles/Home.module.css'

export default function Home(props) {
	const router = useRouter()

  return (
    <div className={styles.container}>
      <Head>
        <title>Visualizando Usuário {props.name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

			<a onClick={() => router.back()}>{"<- "} Voltar</a>

			<h4>Nome: {props.name}</h4>
			<h4>Email: {props.email}</h4>
			<h4>Senha: {props.pass}</h4>
			<h4>Data de Nascimento: {props.birth}</h4>
    </div>
  )
}

export const getServerSideProps: GetServerSideProps = async ({ query }) => {
	const { name, email, pass, birth } = query

	return {
		props: {
			name,
			email,
			pass,
			birth
		}
	}
}
