version: '3.5'

services:
  postgres:
    container_name: dblab
    image: postgres:14.5-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: laboratorio
      # PGDATA: /data/postgres
    # volumes:
      #  - postgres:/data/postgres
    ports:
      - "65432:5432"
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

# volumes:
#   postgres: